export const mockFiles = [
  { path: 'printer_user_s_guide.ditamap', additions: 2, deletions: 1 },
  { path: 'printer_user_s_guide/adjusting_print_quality/adjusting_print_quality.dita', additions: 3, deletions: 2 },
  { path: 'printer_user_s_guide/adjusting_print_quality/checking_the_number_of_sheets_fed/checking_the_number_of_sheets_fed.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/adjusting_print_quality/checking_the_number_of_sheets_fed/checking_the_number_of_sheets_on_the_lcd_screen/checking_the_number_of_sheets_on_the_lcd_screen.dita', additions: 2, deletions: 3 },
  { path: 'printer_user_s_guide/adjusting_print_quality/checking_the_number_of_sheets_fed/checking_the_sheet_counter_window/checking_the_sheet_counter_window.dita', additions: 1, deletions: 2 },
  { path: 'printer_user_s_guide/adjusting_print_quality/cleaning_the_print_head_nozzle/cleaning_the_print_head_nozzle.dita', additions: 4, deletions: 1 },
  { path: 'printer_user_s_guide/adjusting_print_quality/cleaning_the_print_head_path/cleaning_the_print_head_path.dita', additions: 2, deletions: 2 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_alignment/aligning_the_print_head_using_a_computer.dita', additions: 3, deletions: 1 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_alignment/aligning_the_print_head_using_the_product_control_panel.dita', additions: 1, deletions: 3 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_maintenance/power_cleaning/power_cleaning.dita', additions: 2, deletions: 1 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_maintenance/power_cleaning/power_cleaning_using_a_computer.dita', additions: 3, deletions: 2 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_maintenance/power_cleaning/power_cleaning_using_the_product_control_panel.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_maintenance/print_head_cleaning/cleaning_the_print_head_using_a_computer.dita', additions: 2, deletions: 2 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_maintenance/print_head_cleaning/cleaning_the_print_head_using_the_product_control_panel.dita', additions: 4, deletions: 1 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_nozzle_check/checking_the_nozzles_using_a_computer_utility/checking_the_nozzles_using_a_computer_utility.dita', additions: 1, deletions: 3 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_nozzle_check/checking_the_nozzles_using_the_product_control_panel/checking_the_nozzles_using_the_product_control_panel.dita', additions: 2, deletions: 1 },
  { path: 'printer_user_s_guide/adjusting_print_quality/print_head_nozzle_check/print_head_nozzle_check.ditamap', additions: 3, deletions: 2 },
  { path: 'printer_user_s_guide/admin/transporting_your_product/packing_the_printer/packing_the_printer.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/admin/transporting_your_product/transporting_your_product.dita', additions: 2, deletions: 3 },
  { path: 'printer_user_s_guide/admin/transporting_your_product/transporting_your_product/transporting_your_product.dita', additions: 4, deletions: 2 },
  { path: 'printer_user_s_guide/admin/transporting_your_product/unpacking_your_product/unpacking_your_product.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/admin/transporting_your_product/copyright_notice/copyright_notice.dita', additions: 2, deletions: 2 },
  { path: 'printer_user_s_guide/admin/transporting_your_product/copyright_notice/trademarks/trademarks.dita', additions: 3, deletions: 1 },
  { path: 'printer_user_s_guide/copying/copying_documents_or_photos/copying_documents_or_photos.dita', additions: 1, deletions: 2 },
  { path: 'printer_user_s_guide/copying/copying_options/copying_options.dita', additions: 2, deletions: 1 },
  { path: 'printer_user_s_guide/faxing/faxing_basics/faxing_basics.dita', additions: 3, deletions: 3 },
  { path: 'printer_user_s_guide/faxing/having_fax_problems/paper_type_compatibility.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/faxing/having_fax_problems/paper_type_compatibility/paper_type_compatibility.dita', additions: 2, deletions: 2 },
  { path: 'printer_user_s_guide/faxing/loading_paper/available_select_printing_capacity/available_select_printing_capacities.dita', additions: 4, deletions: 1 },
  { path: 'printer_user_s_guide/faxing/loading_paper/loading_paper.dita', additions: 1, deletions: 3 },
  { path: 'printer_user_s_guide/faxing/loading_paper/loading_paper_in_the_rear_paper_feeder/loading_paper_in_the_rear_paper_feeder.dita', additions: 2, deletions: 1 },
  { path: 'printer_user_s_guide/faxing/originals_in_the_auto/placing_originals_on_the_scanner_glass/placing_originals_on_the_scanner_glass.dita', additions: 3, deletions: 2 },
  { path: 'printer_user_s_guide/faxing/originals_in_the_auto/placing_originals_in_the_auto_feeder.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/getting_parts_guide/getting_parts_guide.dita', additions: 2, deletions: 3 },
  { path: 'printer_user_s_guide/product_basics/product_basics.dita', additions: 4, deletions: 2 },
  { path: 'printer_user_s_guide/product_basics/product_parts/product_parts_front.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/product_basics/product_parts/product_parts_inside/product_parts_inside.dita', additions: 2, deletions: 2 },
  { path: 'printer_user_s_guide/product_basics/product_parts/product_parts_rear/product_parts_rear.dita', additions: 3, deletions: 1 },
  { path: 'printer_user_s_guide/product_basics/product_parts/product_parts_mode/product_parts_mode.dita', additions: 1, deletions: 2 },
  { path: 'printer_user_s_guide/product_basics/product_parts/troubleshoot/product_parts_locations.dita', additions: 2, deletions: 1 },
  { path: 'printer_user_s_guide/product_basics/product_parts/troubleshoot/product_parts_1604008223_front/product_parts_front.dita', additions: 3, deletions: 3 },
  { path: 'printer_user_s_guide/product_basics/power_saving_settings/changing_the_power_off_timer_setting_from_the_control_panel/changing_the_power_off_timer_setting_from_the_control_panel.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/product_basics/power_saving_settings/changing_the_sleep_timer_setting_from_the_control_panel/changing_the_sleep_timer_setting_from_the_control_panel.dita', additions: 2, deletions: 2 },
  { path: 'printer_user_s_guide/product_basics/power_saving_settings/power_saving_settings.dita', additions: 4, deletions: 1 },
  { path: 'printer_user_s_guide/product_basics/changing_lcd_screen_language/changing_lcd_screen_language.dita', additions: 1, deletions: 3 },
  { path: 'printer_user_s_guide/product_basics/changing_the_control_panel/changing_characters_on_the_lcd_screen/changing_characters_on_the_lcd_screen.dita', additions: 2, deletions: 1 },
  { path: 'printer_user_s_guide/product_basics/changing_the_control_panel/entering_characters_on_the_lcd_screen/entering_characters_on_the_lcd_screen.dita', additions: 3, deletions: 2 },
  { path: 'printer_user_s_guide/product_basics/accessing_the_information/accessing_the_information.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/product_basics/accessing_the_control_panel/accessing_for_control_panel.dita', additions: 2, deletions: 3 },
  { path: 'printer_user_s_guide/product_basics/changing_the_control_panel/buttons_panel_lcd_screen/buttons_dita.dita', additions: 4, deletions: 2 },
  { path: 'printer_user_s_guide/printing/printing_on_a_mac/printing_on_a_mac.dita', additions: 1, deletions: 1 },
  { path: 'printer_user_s_guide/printing/printing_on_a_mac/booklet/printing_print_layout.dita', additions: 2, deletions: 2 },
  { path: 'printer_user_s_guide/printing/printing_on_a_mac/booklet/selecting_ink_levels_mac.dita', additions: 3, deletions: 1 },
  { path: 'printer_user_s_guide/printing/printing_on_a_mac/booklet/checking_the_levels_on_your_product.dita', additions: 1, deletions: 2 },
  { path: 'printer_user_s_guide/printing/printing_on_a_mac/booklet/checking_the_levels_windows/checking_the_levels_windows.dita', additions: 2, deletions: 1 },
  { path: 'printer_user_s_guide/printing/printing_on_a_mac/booklet/adding_special_effects_with_watermarks/adding_special_effects_with_windows.dita', additions: 3, deletions: 3 },
  { path: 'printer_user_s_guide/printing/replacing_ink_paper_in_your_product/ink_cartridge_info/ink_cartridge_part_numbers.dita', additions: 1, deletions: 1 }
];

export function generateDiffContent() {
  return [
    { lineNum: 1, type: 'normal', content: '<?xml version="1.0" encoding="UTF-8"?>' },
    { lineNum: 2, type: 'normal', content: '<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">' },
    { lineNum: 3, type: 'normal', content: '<topic id="topic_task" topic="task">' },
    { lineNum: 4, type: 'remove', content: '  <title class="- topic/title base/b1331">Checking the Number of Sheets Fed/title>' },
    { lineNum: 5, type: 'add', content: '  <title class="- topic/title base/b1331">Checking the Number of Sheets Fed</title>' },
    { lineNum: 6, type: 'normal', content: '  <shortdesc>Printer User Guide</shortdesc>' },
    { lineNum: 7, type: 'normal', content: '  <prolog>' },
    { lineNum: 8, type: 'remove', content: '    <metadata>' },
    { lineNum: 9, type: 'add', content: '    <metadata id="meta001">' },
    { lineNum: 10, type: 'normal', content: '      <keywords>' },
    { lineNum: 11, type: 'normal', content: '        <indexterm>' },
    { lineNum: 12, type: 'remove', content: '          <a name="C.indexterm">Add to the this window</a>' },
    { lineNum: 13, type: 'add', content: '          <a name="C.indexterm">Add to this window</a>' },
    { lineNum: 14, type: 'normal', content: '        </indexterm>' },
    { lineNum: 15, type: 'normal', content: '      </keywords>' },
    { lineNum: 16, type: 'normal', content: '    </metadata>' },
    { lineNum: 17, type: 'normal', content: '  </prolog>' },
    { lineNum: 18, type: 'add', content: '  <body>' },
    { lineNum: 19, type: 'add', content: '    <p>Updated content for better clarity</p>' },
    { lineNum: 20, type: 'add', content: '  </body>' },
    { lineNum: 21, type: 'normal', content: '</topic>' }
  ];
}
